<?php

namespace Database\Seeders;

use App\Models\Ingredient;
use App\Models\Recipe;
use App\Models\User;
use Illuminate\Database\Seeder;

class IsiPiringkuSeeder extends Seeder
{
    public function run(): void
    {
        $admin = User::where('role', 'admin')->first();

        // ── Bahan Baru yang belum ada ──
        $newIngredients = [
            ['name' => 'Ikan Gabus', 'unit' => 'gram', 'calories' => 80, 'protein' => 16.2, 'fat' => 0.5, 'carbohydrates' => 0, 'fiber' => 0, 'calcium' => 62, 'iron' => 0.9, 'vitamin_a' => 45, 'vitamin_c' => 0],
            ['name' => 'Ikan Patin', 'unit' => 'gram', 'calories' => 132, 'protein' => 17, 'fat' => 6.6, 'carbohydrates' => 0, 'fiber' => 0, 'calcium' => 31, 'iron' => 1.6, 'vitamin_a' => 24, 'vitamin_c' => 0],
            ['name' => 'Ikan Bandeng', 'unit' => 'gram', 'calories' => 124, 'protein' => 20.4, 'fat' => 4.8, 'carbohydrates' => 0, 'fiber' => 0, 'calcium' => 20, 'iron' => 2.0, 'vitamin_a' => 30, 'vitamin_c' => 0],
            ['name' => 'Ikan Kembung', 'unit' => 'gram', 'calories' => 103, 'protein' => 22, 'fat' => 1.0, 'carbohydrates' => 0, 'fiber' => 0, 'calcium' => 20, 'iron' => 1.0, 'vitamin_a' => 30, 'vitamin_c' => 0],
            ['name' => 'Ikan Tongkol', 'unit' => 'gram', 'calories' => 109, 'protein' => 24, 'fat' => 1.0, 'carbohydrates' => 0, 'fiber' => 0, 'calcium' => 40, 'iron' => 1.3, 'vitamin_a' => 35, 'vitamin_c' => 0],
            ['name' => 'Ikan Mas', 'unit' => 'gram', 'calories' => 86, 'protein' => 16, 'fat' => 2.0, 'carbohydrates' => 0, 'fiber' => 0, 'calcium' => 20, 'iron' => 0.7, 'vitamin_a' => 10, 'vitamin_c' => 0],
            ['name' => 'Hati Sapi', 'unit' => 'gram', 'calories' => 135, 'protein' => 20.4, 'fat' => 3.6, 'carbohydrates' => 3.9, 'fiber' => 0, 'calcium' => 6, 'iron' => 6.5, 'vitamin_a' => 4968, 'vitamin_c' => 1.3],
            ['name' => 'Daging Bebek', 'unit' => 'gram', 'calories' => 132, 'protein' => 18.3, 'fat' => 5.9, 'carbohydrates' => 0, 'fiber' => 0, 'calcium' => 15, 'iron' => 2.4, 'vitamin_a' => 24, 'vitamin_c' => 0],
            ['name' => 'Cumi-Cumi', 'unit' => 'gram', 'calories' => 92, 'protein' => 15.6, 'fat' => 1.4, 'carbohydrates' => 3.1, 'fiber' => 0, 'calcium' => 32, 'iron' => 0.7, 'vitamin_a' => 10, 'vitamin_c' => 5],
            ['name' => 'Kerang', 'unit' => 'gram', 'calories' => 86, 'protein' => 15, 'fat' => 2.0, 'carbohydrates' => 3.7, 'fiber' => 0, 'calcium' => 66, 'iron' => 3.0, 'vitamin_a' => 48, 'vitamin_c' => 0],
            ['name' => 'Sagu', 'unit' => 'gram', 'calories' => 353, 'protein' => 0.2, 'fat' => 0.2, 'carbohydrates' => 86.9, 'fiber' => 0.4, 'calcium' => 10, 'iron' => 1.2, 'vitamin_a' => 0, 'vitamin_c' => 0],
            ['name' => 'Talas', 'unit' => 'gram', 'calories' => 112, 'protein' => 1.5, 'fat' => 0.2, 'carbohydrates' => 26.5, 'fiber' => 4.1, 'calcium' => 43, 'iron' => 0.6, 'vitamin_a' => 4, 'vitamin_c' => 4.5],
            ['name' => 'Kacang Merah', 'unit' => 'gram', 'calories' => 127, 'protein' => 8.7, 'fat' => 0.5, 'carbohydrates' => 22.8, 'fiber' => 6.4, 'calcium' => 28, 'iron' => 2.9, 'vitamin_a' => 0, 'vitamin_c' => 1.2],
            ['name' => 'Kacang Panjang', 'unit' => 'gram', 'calories' => 47, 'protein' => 2.8, 'fat' => 0.4, 'carbohydrates' => 8.4, 'fiber' => 3.3, 'calcium' => 50, 'iron' => 0.5, 'vitamin_a' => 43, 'vitamin_c' => 18.8],
            ['name' => 'Daun Pepaya', 'unit' => 'gram', 'calories' => 74, 'protein' => 8.0, 'fat' => 2.0, 'carbohydrates' => 11.3, 'fiber' => 1.5, 'calcium' => 353, 'iron' => 0.8, 'vitamin_a' => 182, 'vitamin_c' => 140],
            ['name' => 'Jantung Pisang', 'unit' => 'gram', 'calories' => 51, 'protein' => 1.6, 'fat' => 0.6, 'carbohydrates' => 9.9, 'fiber' => 5.7, 'calcium' => 56, 'iron' => 0.6, 'vitamin_a' => 14, 'vitamin_c' => 11.3],
            ['name' => 'Daun Katuk', 'unit' => 'gram', 'calories' => 59, 'protein' => 6.4, 'fat' => 1.0, 'carbohydrates' => 9.9, 'fiber' => 1.5, 'calcium' => 204, 'iron' => 2.7, 'vitamin_a' => 353, 'vitamin_c' => 164],
            ['name' => 'Labu Siam', 'unit' => 'gram', 'calories' => 19, 'protein' => 0.8, 'fat' => 0.1, 'carbohydrates' => 4.5, 'fiber' => 1.7, 'calcium' => 17, 'iron' => 0.3, 'vitamin_a' => 3, 'vitamin_c' => 7.7],
            ['name' => 'Rebung', 'unit' => 'gram', 'calories' => 27, 'protein' => 2.6, 'fat' => 0.3, 'carbohydrates' => 5.2, 'fiber' => 2.2, 'calcium' => 13, 'iron' => 0.5, 'vitamin_a' => 1, 'vitamin_c' => 4],
            ['name' => 'Belut', 'unit' => 'gram', 'calories' => 303, 'protein' => 14, 'fat' => 27, 'carbohydrates' => 0, 'fiber' => 0, 'calcium' => 20, 'iron' => 2.0, 'vitamin_a' => 1600, 'vitamin_c' => 2],
            ['name' => 'Petai', 'unit' => 'gram', 'calories' => 108, 'protein' => 6.0, 'fat' => 1.6, 'carbohydrates' => 19.5, 'fiber' => 4.2, 'calcium' => 108, 'iron' => 2.2, 'vitamin_a' => 0, 'vitamin_c' => 19],
            ['name' => 'Keladi/Uwi', 'unit' => 'gram', 'calories' => 118, 'protein' => 1.5, 'fat' => 0.2, 'carbohydrates' => 27.9, 'fiber' => 4.1, 'calcium' => 17, 'iron' => 0.5, 'vitamin_a' => 6, 'vitamin_c' => 17.1],
            ['name' => 'Kecambah/Tauge', 'unit' => 'gram', 'calories' => 31, 'protein' => 3.0, 'fat' => 0.2, 'carbohydrates' => 5.9, 'fiber' => 1.8, 'calcium' => 13, 'iron' => 0.9, 'vitamin_a' => 1, 'vitamin_c' => 13.2],
            ['name' => 'Jamur Tiram', 'unit' => 'gram', 'calories' => 33, 'protein' => 3.3, 'fat' => 0.4, 'carbohydrates' => 6.1, 'fiber' => 2.3, 'calcium' => 3, 'iron' => 1.3, 'vitamin_a' => 0, 'vitamin_c' => 0],
            ['name' => 'Pare', 'unit' => 'gram', 'calories' => 17, 'protein' => 1.0, 'fat' => 0.2, 'carbohydrates' => 3.7, 'fiber' => 2.8, 'calcium' => 19, 'iron' => 0.4, 'vitamin_a' => 17, 'vitamin_c' => 84],
        ];

        foreach ($newIngredients as $ing) {
            Ingredient::firstOrCreate(['name' => $ing['name']], $ing);
        }

        // Load all ingredients for reference
        $ing = Ingredient::all()->keyBy('name');

        // Helper: [title, slug, desc, age, cat_id, ingredients[], instructions]
        $makeRecipe = function ($r) use ($admin, $ing) {
            $recipe = Recipe::create([
                'user_id' => $admin->id, 'category_id' => $r[4],
                'title' => $r[0], 'slug' => $r[1], 'description' => $r[2],
                'age_group' => $r[3], 'servings' => $r[7] ?? 2,
                'instructions' => $r[6], 'is_published' => true,
            ]);
            $attach = [];
            foreach ($r[5] as $name => $qty) {
                if (isset($ing[$name])) {
                    $attach[$ing[$name]->id] = ['quantity_grams' => $qty];
                }
            }
            $recipe->ingredients()->attach($attach);
        };

        // ═══════════════════════════════════════════════════════════════════
        // MPASI 6-8 BULAN — Resep Lokal "Isi Piringku"
        // ═══════════════════════════════════════════════════════════════════

        $mpasi6 = [
            ['Bubur Ikan Gabus Bayam', 'bubur-ikan-gabus-bayam', 'Bubur MPASI dengan ikan gabus lokal kaya albumin dan bayam sumber zat besi, ideal untuk bayi 6 bulan.', '6-8 bulan', 1, ['Beras Putih' => 25, 'Ikan Gabus' => 20, 'Bayam' => 15], "1. Cuci beras, rendam 30 menit\n2. Bersihkan ikan gabus, buang tulang dan duri\n3. Kukus ikan gabus 15 menit hingga matang\n4. Petik daun bayam muda, cuci bersih\n5. Masak beras dengan air hingga menjadi bubur lembut\n6. Kukus bayam 5 menit, tiriskan\n7. Hancurkan ikan gabus halus dengan garpu\n8. Campurkan ikan dan bayam ke bubur, blender halus\n9. Tambahkan 1 sendok teh minyak kelapa\n10. Sajikan hangat"],
            ['Puree Labu Kuning Ikan Patin', 'puree-labu-kuning-ikan-patin', 'Puree labu kuning manis alami dengan ikan patin lembut yang mudah dicerna bayi.', '6-8 bulan', 1, ['Labu Kuning' => 40, 'Ikan Patin' => 20], "1. Kupas labu kuning, buang biji, potong dadu kecil\n2. Bersihkan ikan patin, hilangkan tulang dan kulit\n3. Kukus labu kuning dan ikan patin bersamaan 15 menit\n4. Angkat, pastikan ikan matang sempurna\n5. Masukkan labu dan ikan ke blender\n6. Tambahkan sedikit air matang hangat\n7. Blender hingga halus seperti krim\n8. Tambahkan setetes minyak zaitun atau santan\n9. Sajikan hangat dalam mangkuk kecil"],
            ['Bubur Ubi Jalar Hati Sapi', 'bubur-ubi-jalar-hati-sapi', 'Bubur ubi jalar oranye dengan hati sapi kaya vitamin A dan zat besi tinggi.', '6-8 bulan', 1, ['Ubi Jalar' => 40, 'Hati Sapi' => 15], "1. Kupas ubi jalar oranye, potong kecil-kecil\n2. Rendam hati sapi dalam air jeruk nipis 10 menit, buang lemak\n3. Rebus hati sapi hingga matang, angkat\n4. Kukus ubi jalar hingga empuk sekitar 15 menit\n5. Potong hati sapi kecil-kecil\n6. Masukkan ubi dan hati ke blender\n7. Tambahkan air matang secukupnya\n8. Blender hingga halus rata\n9. Sajikan hangat"],
            ['Puree Singkong Telur Kuning', 'puree-singkong-telur-kuning', 'Puree singkong halus dengan kuning telur kampung, kaya karbohidrat dan protein.', '6-8 bulan', 1, ['Singkong' => 40, 'Telur Ayam' => 20], "1. Kupas singkong, cuci bersih, potong kecil\n2. Rebus singkong hingga empuk sekitar 20 menit\n3. Rebus telur ayam kampung hingga matang\n4. Pisahkan kuning telur dari putihnya\n5. Haluskan singkong rebus dengan garpu\n6. Campurkan kuning telur, aduk rata\n7. Tambahkan sedikit air matang jika terlalu kental\n8. Blender hingga halus lembut\n9. Sajikan hangat"],
            ['Bubur Beras Ikan Kembung', 'bubur-beras-merah-ikan-kembung', 'Bubur beras dengan ikan kembung segar sumber omega-3 untuk perkembangan otak bayi.', '6-8 bulan', 1, ['Beras Putih' => 25, 'Ikan Kembung' => 20, 'Wortel' => 10], "1. Cuci beras, rendam 30 menit\n2. Bersihkan ikan kembung, buang sisik dan isi perut\n3. Kukus ikan kembung hingga matang, pisahkan daging dari tulang\n4. Kupas wortel, parut halus\n5. Masak beras dengan air menjadi bubur\n6. Tambahkan wortel parut, masak 5 menit\n7. Campurkan daging ikan, aduk rata\n8. Blender hingga halus\n9. Sajikan hangat"],
            ['Puree Talas Daun Kelor', 'puree-talas-daun-kelor', 'Puree talas lembut dengan daun kelor superfood lokal kaya kalsium.', '6-8 bulan', 1, ['Talas' => 40, 'Daun Kelor' => 10], "1. Kupas talas, potong dadu kecil, rendam air garam\n2. Petik daun kelor muda dari batangnya\n3. Cuci daun kelor bersih, tiriskan\n4. Kukus talas hingga empuk sekitar 20 menit\n5. Rebus daun kelor 3 menit, tiriskan\n6. Masukkan talas dan daun kelor ke blender\n7. Tambahkan sedikit air matang\n8. Blender hingga halus sempurna\n9. Sajikan hangat"],
            ['Bubur Jagung Ikan Tongkol', 'bubur-jagung-ikan-tongkol', 'Bubur jagung manis dengan ikan tongkol segar, kombinasi karbohidrat dan protein hewani.', '6-8 bulan', 1, ['Jagung Manis' => 30, 'Ikan Tongkol' => 20], "1. Pipil jagung manis dari tongkolnya\n2. Bersihkan ikan tongkol, buang tulang dan kulit\n3. Kukus ikan tongkol 15 menit hingga matang\n4. Rebus jagung pipil hingga lunak sekitar 15 menit\n5. Suwir halus daging ikan tongkol\n6. Campurkan jagung dan ikan ke blender\n7. Tambahkan air rebusan jagung secukupnya\n8. Blender hingga menjadi bubur halus\n9. Sajikan hangat"],
            ['Puree Wortel Ikan Bandeng', 'puree-wortel-ikan-bandeng', 'Puree wortel kaya vitamin A dengan ikan bandeng tanpa duri yang lembut untuk bayi.', '6-8 bulan', 1, ['Wortel' => 35, 'Ikan Bandeng' => 20], "1. Kupas wortel, potong tipis-tipis\n2. Bersihkan ikan bandeng, kukus hingga matang\n3. Pisahkan daging bandeng dari tulang dengan hati-hati\n4. Kukus wortel hingga empuk sekitar 10 menit\n5. Masukkan wortel dan daging bandeng ke blender\n6. Tambahkan sedikit air matang\n7. Blender hingga halus lembut\n8. Tambahkan setetes minyak kelapa\n9. Sajikan hangat"],
            ['Bubur Kentang Hati Ayam Bayam', 'bubur-kentang-hati-ayam-bayam', 'Bubur kentang lembut dengan hati ayam dan bayam, komplit zat besi dan vitamin.', '6-8 bulan', 1, ['Kentang' => 30, 'Hati Ayam' => 15, 'Bayam' => 10], "1. Kupas kentang, potong dadu kecil\n2. Cuci hati ayam, buang bagian yang keras dan lemak\n3. Rebus kentang hingga empuk sekitar 15 menit\n4. Kukus hati ayam hingga matang sekitar 10 menit\n5. Petik daun bayam muda, rebus sebentar 3 menit\n6. Campurkan semua bahan ke blender\n7. Tambahkan air matang secukupnya\n8. Blender hingga tekstur halus rata\n9. Sajikan hangat"],
            ['Puree Labu Siam Telur', 'puree-labu-siam-telur', 'Puree labu siam ringan dengan kuning telur, mudah dicerna dan kaya nutrisi.', '6-8 bulan', 1, ['Labu Siam' => 40, 'Telur Ayam' => 20], "1. Kupas labu siam, buang biji, potong kecil\n2. Kukus labu siam hingga empuk sekitar 15 menit\n3. Rebus telur hingga matang sempurna\n4. Pisahkan kuning telur\n5. Masukkan labu siam dan kuning telur ke blender\n6. Tambahkan sedikit air matang\n7. Blender hingga halus lembut\n8. Sajikan hangat"],
            ['Bubur Sagu Ikan Gabus Kelor', 'bubur-sagu-ikan-gabus-kelor', 'Bubur sagu dengan ikan gabus dan daun kelor, menu khas timur Indonesia untuk MPASI.', '6-8 bulan', 1, ['Sagu' => 20, 'Ikan Gabus' => 20, 'Daun Kelor' => 10], "1. Larutkan tepung sagu dalam sedikit air dingin\n2. Bersihkan ikan gabus, buang tulang dan sisik\n3. Kukus ikan gabus hingga matang, suwir halus\n4. Petik daun kelor muda, rebus 3 menit\n5. Didihkan air, tuang larutan sagu sambil diaduk\n6. Masak hingga mengental dan bening\n7. Campurkan ikan dan daun kelor\n8. Blender hingga halus\n9. Sajikan hangat"],
            ['Puree Ubi Ikan Mas', 'puree-ubi-ungu-ikan-mas', 'Puree ubi alami dengan ikan mas kolam, karbohidrat dan protein seimbang.', '6-8 bulan', 1, ['Ubi Jalar' => 40, 'Ikan Mas' => 20], "1. Kupas ubi jalar, potong kecil-kecil\n2. Bersihkan ikan mas, buang sisik dan isi perut\n3. Kukus ubi jalar hingga empuk sekitar 15 menit\n4. Kukus ikan mas hingga matang, pisahkan daging dari tulang\n5. Masukkan ubi dan daging ikan ke blender\n6. Tambahkan air matang secukupnya\n7. Blender hingga halus lembut\n8. Sajikan hangat"],
        ];

        foreach ($mpasi6 as $r) { $makeRecipe($r); }

        // ═══════════════════════════════════════════════════════════════════
        // MPASI 9-11 BULAN — Resep Lokal "Isi Piringku"
        // ═══════════════════════════════════════════════════════════════════

        $mpasi9 = [
            ['Nasi Tim Ikan Gabus Wortel', 'nasi-tim-ikan-gabus-wortel', 'Nasi tim lembut dengan ikan gabus kaya albumin dan wortel vitamin A.', '9-11 bulan', 2, ['Beras Putih' => 40, 'Ikan Gabus' => 30, 'Wortel' => 20], "1. Cuci beras, masak dengan air banyak hingga menjadi nasi lembek\n2. Bersihkan ikan gabus, buang tulang dan sisik\n3. Kukus ikan gabus 15 menit, suwir halus dengan garpu\n4. Kupas wortel, parut kasar\n5. Tumis wortel parut sebentar dengan sedikit minyak\n6. Campurkan nasi lembek, ikan suwir, dan wortel\n7. Tim dalam panci kukusan 15 menit\n8. Hancurkan kasar dengan garpu\n9. Sajikan hangat"],
            ['Bubur Kentang Ayam Kangkung', 'bubur-kentang-ayam-kangkung', 'Bubur kentang cincang kasar dengan ayam dan kangkung segar.', '9-11 bulan', 2, ['Kentang' => 40, 'Daging Ayam' => 25, 'Kangkung' => 15], "1. Kupas kentang, potong dadu kecil\n2. Rebus daging ayam hingga matang, suwir halus\n3. Rebus kentang dalam kaldu ayam hingga empuk\n4. Petik daun kangkung muda, cincang halus\n5. Masukkan kangkung ke rebusan kentang, masak 3 menit\n6. Tambahkan ayam suwir, aduk rata\n7. Hancurkan kasar dengan garpu\n8. Sajikan hangat"],
            ['Nasi Lembek Ikan Patin Labu', 'nasi-lembek-ikan-patin-labu', 'Nasi lembek dengan ikan patin sungai dan labu kuning manis alami.', '9-11 bulan', 2, ['Beras Putih' => 40, 'Ikan Patin' => 25, 'Labu Kuning' => 20], "1. Masak beras dengan air ekstra hingga nasi lembek\n2. Bersihkan ikan patin, buang tulang dan kulit\n3. Kukus ikan patin 15 menit hingga matang\n4. Kupas labu kuning, potong kecil, kukus hingga empuk\n5. Hancurkan ikan patin dengan garpu\n6. Haluskan labu kuning kasar\n7. Campurkan nasi, ikan, dan labu, aduk rata\n8. Sajikan hangat"],
            ['Tim Singkong Telur Bayam', 'tim-singkong-telur-bayam', 'Tim singkong halus dengan telur orak-arik dan bayam cincang.', '9-11 bulan', 2, ['Singkong' => 40, 'Telur Ayam' => 30, 'Bayam' => 15], "1. Kupas singkong, potong kecil, rebus hingga empuk\n2. Kocok telur, buat orak-arik lembut di wajan antilengket\n3. Petik bayam muda, cincang halus\n4. Haluskan singkong rebus dengan garpu\n5. Campurkan singkong, telur orak-arik, dan bayam\n6. Tim semua bahan 10 menit\n7. Aduk rata, hancurkan kasar\n8. Sajikan hangat"],
            ['Nasi Tim Hati Ayam Brokoli', 'nasi-tim-hati-ayam-brokoli', 'Nasi tim dengan hati ayam penuh zat besi dan brokoli vitamin C.', '9-11 bulan', 2, ['Beras Putih' => 40, 'Hati Ayam' => 20, 'Brokoli' => 15], "1. Masak beras menjadi nasi agak lembek\n2. Cuci hati ayam, buang lemak, rebus hingga matang\n3. Potong brokoli kecil-kecil per kuntum\n4. Kukus brokoli 5 menit hingga lunak\n5. Cincang hati ayam halus\n6. Campurkan nasi, hati ayam, dan brokoli\n7. Tim dalam kukusan 15 menit\n8. Hancurkan kasar, sajikan hangat"],
            ['Bubur Jagung Udang Kelor', 'bubur-jagung-udang-kelor', 'Bubur jagung manis dengan udang kecil dan daun kelor bergizi tinggi.', '9-11 bulan', 2, ['Jagung Manis' => 30, 'Udang' => 20, 'Daun Kelor' => 10], "1. Pipil jagung manis, rebus hingga lunak\n2. Kupas udang, buang kepala dan cangkang, cincang halus\n3. Petik daun kelor muda, cuci bersih\n4. Rebus daun kelor 3 menit, tiriskan\n5. Tumis udang cincang sebentar hingga berubah warna\n6. Haluskan jagung rebus kasar\n7. Campurkan jagung, udang, dan kelor\n8. Aduk rata, sajikan hangat"],
            ['Nasi Tim Ikan Bandeng Kangkung', 'nasi-tim-ikan-bandeng-kangkung', 'Nasi tim dengan ikan bandeng tanpa duri dan kangkung segar.', '9-11 bulan', 2, ['Beras Putih' => 40, 'Ikan Bandeng' => 25, 'Kangkung' => 15], "1. Masak beras menjadi nasi lembek\n2. Kukus ikan bandeng hingga matang\n3. Pisahkan daging bandeng dari tulang dengan hati-hati\n4. Petik daun kangkung muda, cincang halus\n5. Rebus kangkung sebentar 3 menit\n6. Campurkan nasi, daging bandeng, dan kangkung\n7. Tim 15 menit, hancurkan kasar\n8. Sajikan hangat"],
            ['Tim Talas Ikan Kembung Wortel', 'tim-talas-ikan-kembung-wortel', 'Tim talas lembut dengan ikan kembung segar dan wortel parut.', '9-11 bulan', 2, ['Talas' => 40, 'Ikan Kembung' => 25, 'Wortel' => 15], "1. Kupas talas, potong kecil, kukus hingga empuk\n2. Bersihkan ikan kembung, kukus hingga matang\n3. Pisahkan daging ikan dari tulang\n4. Kupas wortel, parut halus\n5. Haluskan talas kukus dengan garpu\n6. Campurkan talas, ikan, dan wortel parut\n7. Tim semua bahan 10 menit\n8. Sajikan hangat"],
            ['Nasi Tim Daging Sapi Labu Siam', 'nasi-tim-daging-sapi-labu-siam', 'Nasi tim dengan cincangan daging sapi dan labu siam lembut.', '9-11 bulan', 2, ['Beras Putih' => 40, 'Daging Sapi' => 20, 'Labu Siam' => 20], "1. Masak beras menjadi nasi lembek\n2. Rebus daging sapi hingga empuk, cincang sangat halus\n3. Kupas labu siam, buang biji, potong kecil\n4. Kukus labu siam hingga lunak\n5. Campurkan nasi, daging cincang, dan labu siam\n6. Tim 15 menit hingga menyatu\n7. Hancurkan kasar dengan garpu\n8. Sajikan hangat"],
            ['Bubur Ubi Belut Bayam', 'bubur-ubi-belut-bayam', 'Bubur ubi jalar dengan belut goreng kaya vitamin A dan bayam zat besi.', '9-11 bulan', 2, ['Ubi Jalar' => 35, 'Belut' => 20, 'Bayam' => 15], "1. Kupas ubi jalar, potong kecil, kukus hingga empuk\n2. Bersihkan belut, potong pendek-pendek\n3. Goreng belut dengan sedikit minyak hingga garing\n4. Hancurkan belut goreng halus\n5. Petik bayam muda, rebus sebentar\n6. Haluskan ubi kukus, campurkan belut dan bayam\n7. Aduk rata, tambahkan air matang jika kental\n8. Sajikan hangat"],
            ['Tim Beras Ikan Tongkol Tahu', 'tim-beras-ikan-tongkol-tahu', 'Nasi tim dengan ikan tongkol dan tahu sebagai protein ganda.', '9-11 bulan', 2, ['Beras Putih' => 40, 'Ikan Tongkol' => 20, 'Tahu' => 20], "1. Masak beras menjadi nasi lembek\n2. Kukus ikan tongkol hingga matang, suwir halus\n3. Potong tahu kecil-kecil, kukus 5 menit\n4. Hancurkan tahu lembut dengan garpu\n5. Campurkan nasi, ikan tongkol suwir, dan tahu\n6. Tim dalam kukusan 15 menit\n7. Aduk rata, hancurkan kasar\n8. Sajikan hangat"],
            ['Bubur Sagu Ikan Mas Kangkung', 'bubur-sagu-ikan-mas-kangkung', 'Bubur sagu dengan ikan mas dan kangkung, menu khas lokal untuk bayi.', '9-11 bulan', 2, ['Sagu' => 25, 'Ikan Mas' => 25, 'Kangkung' => 15], "1. Larutkan sagu dalam air dingin\n2. Bersihkan ikan mas, buang sisik dan tulang\n3. Kukus ikan mas hingga matang, suwir halus\n4. Petik kangkung muda, cincang halus\n5. Didihkan air, tuang larutan sagu sambil diaduk\n6. Masak hingga mengental\n7. Campurkan ikan dan kangkung, aduk rata\n8. Sajikan hangat"],
        ];

        foreach ($mpasi9 as $r) { $makeRecipe($r); }

        // ═══════════════════════════════════════════════════════════════════
        // BALITA 1-3 TAHUN — Resep Lokal "Isi Piringku"
        // ═══════════════════════════════════════════════════════════════════

        $balita = [
            ['Nasi Ikan Gabus Kuah Kelor', 'nasi-ikan-gabus-kuah-kelor', 'Nasi dengan ikan gabus kuah bening daun kelor, menu anti-stunting kaya albumin dan kalsium.', '1-3 tahun', 3, ['Beras Putih' => 80, 'Ikan Gabus' => 50, 'Daun Kelor' => 20, 'Tahu' => 20], "1. Masak nasi putih seperti biasa\n2. Bersihkan ikan gabus, potong sesuai porsi anak\n3. Rebus ikan gabus dalam air hingga matang, sisihkan\n4. Petik daun kelor, cuci bersih\n5. Masukkan daun kelor ke kaldu ikan, masak 3 menit\n6. Potong tahu dadu kecil, goreng sebentar\n7. Tata nasi di piring, sajikan ikan gabus, tahu, dan kuah kelor\n8. Pastikan duri ikan sudah dibuang sebelum disajikan", 3],
            ['Sup Ayam Sayur Kampung', 'sup-ayam-sayur-kampung', 'Sup ayam kampung dengan aneka sayur pekarangan, hangat bergizi untuk balita.', '1-3 tahun', 3, ['Daging Ayam' => 50, 'Wortel' => 25, 'Kentang' => 40, 'Bayam' => 20], "1. Rebus ayam kampung dengan air secukupnya hingga empuk\n2. Angkat ayam, suwir dagingnya kecil-kecil\n3. Kupas kentang dan wortel, potong dadu kecil\n4. Masukkan kentang dan wortel ke kaldu ayam, rebus 10 menit\n5. Petik bayam, masukkan terakhir, masak 2 menit\n6. Masukkan kembali ayam suwir\n7. Beri sedikit garam, sajikan hangat dengan nasi", 3],
            ['Nasi Uduk Ikan Teri Tempe', 'nasi-uduk-ikan-teri-tempe-balita', 'Nasi uduk gurih dengan ikan teri goreng dan tempe orek, protein berlimpah.', '1-3 tahun', 3, ['Beras Putih' => 80, 'Santan' => 30, 'Ikan Teri' => 20, 'Tempe' => 30], "1. Cuci beras, masak dengan santan encer dan sedikit garam\n2. Cuci ikan teri, goreng dengan sedikit minyak hingga garing\n3. Potong tempe dadu kecil, goreng hingga keemasan\n4. Orek tempe goreng dengan sedikit kecap manis\n5. Tata nasi uduk di piring\n6. Sajikan dengan ikan teri goreng dan tempe orek", 3],
            ['Pepes Ikan Patin Daun Pisang', 'pepes-ikan-patin-daun-pisang', 'Pepes ikan patin bumbu kuning dibungkus daun pisang, lembut dan harum.', '1-3 tahun', 3, ['Ikan Patin' => 60, 'Beras Putih' => 80, 'Tomat' => 20], "1. Bersihkan ikan patin, lumuri dengan bumbu kunyit dan garam\n2. Iris tomat tipis-tipis\n3. Siapkan daun pisang, layukan di atas api sebentar\n4. Letakkan ikan di atas daun pisang, taburi irisan tomat\n5. Bungkus rapi, semat dengan lidi\n6. Kukus pepes 25 menit hingga matang dan harum\n7. Sajikan dengan nasi putih hangat", 3],
            ['Nasi Goreng Ikan Tongkol Sayur', 'nasi-goreng-ikan-tongkol-sayur', 'Nasi goreng dengan suwiran ikan tongkol dan sayuran segar, tanpa MSG.', '1-3 tahun', 3, ['Beras Putih' => 80, 'Ikan Tongkol' => 40, 'Kangkung' => 20, 'Telur Ayam' => 30], "1. Masak nasi, biarkan agak dingin\n2. Kukus ikan tongkol, suwir halus\n3. Kocok telur, buat orak-arik\n4. Petik kangkung, potong pendek\n5. Panaskan sedikit minyak, tumis kangkung sebentar\n6. Masukkan nasi, aduk rata dengan api besar\n7. Tambahkan ikan suwir dan telur orak-arik\n8. Aduk rata, sajikan hangat", 3],
            ['Sayur Asem Jagung Kacang Panjang', 'sayur-asem-jagung-kacang-panjang', 'Sayur asem segar khas Sunda dengan jagung dan kacang panjang, cocok pendamping lauk.', '1-3 tahun', 3, ['Jagung Manis' => 40, 'Kacang Panjang' => 30, 'Labu Siam' => 30], "1. Pipil jagung manis dari tongkolnya\n2. Potong kacang panjang sepanjang 2 cm\n3. Kupas labu siam, potong dadu\n4. Didihkan air, masukkan jagung terlebih dahulu\n5. Setelah 10 menit, tambahkan labu siam\n6. Masukkan kacang panjang, masak 5 menit lagi\n7. Tambahkan asam jawa sedikit dan garam\n8. Sajikan hangat sebagai pendamping lauk", 3],
            ['Telur Dadar Daun Kelor', 'telur-dadar-daun-kelor', 'Telur dadar tebal berisi daun kelor, cara praktis makan superfood untuk balita.', '1-3 tahun', 3, ['Telur Ayam' => 50, 'Daun Kelor' => 15, 'Beras Putih' => 80], "1. Petik daun kelor muda, cuci bersih, cincang halus\n2. Kocok telur dalam mangkuk\n3. Campurkan daun kelor cincang ke kocokan telur\n4. Tambahkan sedikit garam, aduk rata\n5. Panaskan wajan dengan sedikit minyak\n6. Tuang adonan, ratakan, masak api kecil\n7. Balik saat bagian bawah kecokelatan\n8. Masak hingga matang, potong kecil, sajikan dengan nasi", 3],
            ['Opor Ayam Labu Kuning', 'opor-ayam-labu-kuning', 'Opor ayam santan dengan labu kuning, gurih lembut dan kaya vitamin A.', '1-3 tahun', 3, ['Daging Ayam' => 50, 'Labu Kuning' => 40, 'Santan' => 40, 'Beras Putih' => 80], "1. Potong ayam sesuai porsi anak\n2. Kupas labu kuning, potong dadu\n3. Didihkan santan encer dengan bumbu opor\n4. Masukkan ayam, masak 20 menit hingga empuk\n5. Tambahkan labu kuning, masak 10 menit lagi\n6. Aduk perlahan agar labu tidak hancur\n7. Masak hingga kuah mengental\n8. Sajikan dengan nasi putih hangat", 3],
            ['Nasi Ikan Bandeng Presto Sayur', 'nasi-ikan-bandeng-presto-sayur', 'Nasi dengan bandeng presto dan tumis kangkung, tulang bandeng jadi sumber kalsium.', '1-3 tahun', 3, ['Beras Putih' => 80, 'Ikan Bandeng' => 50, 'Kangkung' => 25], "1. Masak nasi putih seperti biasa\n2. Presto ikan bandeng dengan panci presto 30 menit\n3. Goreng bandeng presto hingga keemasan\n4. Petik kangkung, potong batang mudanya\n5. Tumis kangkung dengan sedikit bawang putih\n6. Tata nasi, bandeng goreng, dan tumis kangkung di piring\n7. Tulang bandeng presto sudah lunak dan bisa dimakan anak", 3],
            ['Sop Daging Sapi Kentang Wortel', 'sop-daging-sapi-kentang-wortel', 'Sop daging sapi empuk dengan kentang dan wortel, klasik bergizi tinggi.', '1-3 tahun', 3, ['Daging Sapi' => 40, 'Kentang' => 40, 'Wortel' => 25, 'Beras Putih' => 80], "1. Rebus daging sapi dengan api kecil hingga empuk (45 menit)\n2. Potong daging kecil-kecil sesuai porsi anak\n3. Kupas kentang dan wortel, potong dadu\n4. Masukkan kentang dan wortel ke kaldu daging\n5. Masak hingga sayuran empuk (10 menit)\n6. Beri sedikit garam dan merica\n7. Sajikan sop hangat dengan nasi putih", 3],
            ['Oseng Tempe Kacang Panjang', 'oseng-tempe-kacang-panjang', 'Tumis tempe dan kacang panjang kecap, protein nabati dan serat tinggi.', '1-3 tahun', 3, ['Tempe' => 50, 'Kacang Panjang' => 30, 'Beras Putih' => 80], "1. Potong tempe tipis kotak-kotak kecil\n2. Goreng tempe sebentar hingga agak garing\n3. Potong kacang panjang sepanjang 2 cm\n4. Tumis bawang merah dan bawang putih iris\n5. Masukkan kacang panjang, tumis hingga layu\n6. Tambahkan tempe goreng dan kecap manis\n7. Aduk rata, tambahkan sedikit air, masak 3 menit\n8. Sajikan dengan nasi putih", 3],
            ['Gulai Ikan Nila Daun Singkong', 'gulai-ikan-nila-daun-singkong', 'Gulai ikan nila khas Padang dengan daun singkong, paduan protein dan kalsium.', '1-3 tahun', 3, ['Ikan Nila' => 50, 'Daun Singkong' => 30, 'Santan' => 40, 'Beras Putih' => 80], "1. Bersihkan ikan nila, potong sesuai porsi\n2. Petik daun singkong muda, remas dengan garam agar empuk\n3. Rebus daun singkong 15 menit, tiriskan\n4. Didihkan santan dengan bumbu gulai\n5. Masukkan ikan nila, masak 15 menit\n6. Tambahkan daun singkong, masak 5 menit lagi\n7. Sajikan gulai hangat dengan nasi", 3],
            ['Perkedel Ikan Mas Kentang', 'perkedel-ikan-mas-kentang', 'Perkedel ikan mas dan kentang goreng, lembut dan disukai anak.', '1-3 tahun', 3, ['Ikan Mas' => 40, 'Kentang' => 60, 'Telur Ayam' => 30], "1. Kukus ikan mas hingga matang, pisahkan daging dari tulang\n2. Rebus kentang hingga empuk, haluskan dengan garpu\n3. Campurkan daging ikan dan kentang halus\n4. Kocok telur, gunakan sebagian untuk campuran adonan\n5. Bentuk adonan bulat pipih kecil\n6. Celupkan ke sisa kocokan telur\n7. Goreng dengan minyak secukupnya hingga keemasan\n8. Tiriskan, sajikan hangat", 3],
            ['Sup Tahu Telur Sayuran', 'sup-tahu-telur-sayuran', 'Sup bening tahu dan telur dengan aneka sayur, ringan dan kaya protein.', '1-3 tahun', 3, ['Tahu' => 40, 'Telur Ayam' => 30, 'Wortel' => 20, 'Bayam' => 15], "1. Potong tahu dadu kecil\n2. Rebus telur hingga matang, belah empat\n3. Kupas dan potong wortel tipis\n4. Didihkan air, masukkan wortel, masak 5 menit\n5. Tambahkan tahu, masak 3 menit\n6. Petik bayam, masukkan terakhir, masak 2 menit\n7. Beri sedikit garam dan merica\n8. Sajikan sup hangat dengan nasi, tambahkan telur", 3],
            ['Nasi Tim Hati Sapi Wortel', 'nasi-tim-hati-sapi-wortel', 'Nasi tim hati sapi dan wortel, sumber zat besi tertinggi untuk cegah anemia.', '1-3 tahun', 3, ['Beras Putih' => 80, 'Hati Sapi' => 30, 'Wortel' => 20], "1. Masak beras menjadi nasi agak lembek\n2. Rendam hati sapi di air jeruk nipis 10 menit\n3. Rebus hati sapi hingga matang, potong dadu kecil\n4. Kupas wortel, parut kasar\n5. Campurkan nasi, hati sapi, dan wortel\n6. Tim dalam panci kukusan 15 menit\n7. Aduk rata, sajikan hangat\n8. Bisa ditambahkan sedikit kecap manis", 3],
        ];

        foreach ($balita as $r) { $makeRecipe($r); }

        // ═══════════════════════════════════════════════════════════════════
        // ANAK 4-6 TAHUN — Resep Lokal "Isi Piringku"
        // ═══════════════════════════════════════════════════════════════════

        $anak = [
            ['Nasi Pecel Lele Lalapan', 'nasi-pecel-lele-lalapan', 'Nasi dengan lele goreng dan lalapan segar plus sambal, favorit anak Indonesia.', '4-6 tahun', 4, ['Beras Putih' => 120, 'Ikan Lele' => 80, 'Kangkung' => 30, 'Tomat' => 20], "1. Masak nasi putih\n2. Bersihkan ikan lele, lumuri garam dan kunyit\n3. Goreng lele dengan minyak panas hingga garing\n4. Rebus kangkung sebentar untuk lalapan, tiriskan\n5. Iris tomat segar sebagai pelengkap\n6. Tata nasi, lele goreng, dan lalapan di piring\n7. Sajikan dengan sambal ringan untuk anak", 3],
            ['Gado-Gado Sayur Lokal', 'gado-gado-sayur-lokal', 'Gado-gado sayuran lokal dengan bumbu kacang, protein nabati dan serat berlimpah.', '4-6 tahun', 4, ['Kacang Tanah' => 40, 'Kangkung' => 30, 'Tahu' => 40, 'Tempe' => 30, 'Kecambah/Tauge' => 20, 'Telur Ayam' => 50], "1. Rebus kangkung dan tauge sebentar, tiriskan\n2. Goreng tahu dan tempe hingga keemasan\n3. Rebus telur, kupas, belah dua\n4. Goreng kacang tanah, tumbuk halus\n5. Campurkan kacang tumbuk dengan air, gula, garam jadi saus\n6. Tata sayuran, tahu, tempe, telur di piring\n7. Siram dengan saus kacang\n8. Sajikan sebagai makan siang", 3],
            ['Nasi Liwet Ikan Teri Labu', 'nasi-liwet-ikan-teri-labu', 'Nasi liwet gurih khas Solo dengan ikan teri dan labu siam, komplit dan lezat.', '4-6 tahun', 4, ['Beras Putih' => 120, 'Santan' => 40, 'Ikan Teri' => 25, 'Labu Siam' => 30], "1. Cuci beras, masak dengan santan, daun salam, dan garam\n2. Goreng ikan teri dengan sedikit minyak hingga garing\n3. Kupas labu siam, potong korek api\n4. Tumis labu siam hingga layu dan matang\n5. Setelah nasi liwet matang, aduk perlahan\n6. Tata nasi liwet di piring, taburi ikan teri goreng\n7. Sajikan dengan tumis labu siam", 3],
            ['Rawon Daging Sapi Tauge', 'rawon-daging-sapi-tauge', 'Rawon daging sapi khas Jawa Timur dengan tauge segar, berkuah hitam bergizi.', '4-6 tahun', 4, ['Daging Sapi' => 60, 'Kecambah/Tauge' => 25, 'Beras Putih' => 120, 'Telur Ayam' => 50], "1. Rebus daging sapi dengan bumbu rawon hingga empuk\n2. Potong daging kecil-kecil\n3. Rebus telur, kupas, goreng sebentar\n4. Cuci tauge, seduh dengan air panas, tiriskan\n5. Masak nasi putih\n6. Tata nasi di mangkuk, siram kuah rawon\n7. Tambahkan daging, telur, dan tauge\n8. Sajikan hangat", 3],
            ['Ayam Goreng Bumbu Kuning Sayur', 'ayam-goreng-bumbu-kuning-sayur', 'Ayam goreng bumbu kuning kunyit dengan sayur bening bayam jagung.', '4-6 tahun', 4, ['Daging Ayam' => 80, 'Bayam' => 30, 'Jagung Manis' => 30, 'Beras Putih' => 120], "1. Lumuri ayam dengan bumbu kuning (kunyit, garam, bawang putih)\n2. Ungkep ayam dengan sedikit air hingga bumbu meresap\n3. Goreng ayam ungkep hingga keemasan dan garing\n4. Pipil jagung, rebus dalam air mendidih\n5. Tambahkan bayam, masak 2 menit saja\n6. Beri garam secukupnya\n7. Sajikan ayam goreng dengan sayur bening dan nasi", 3],
            ['Pindang Ikan Patin Nangka', 'pindang-ikan-patin-nangka', 'Pindang ikan patin khas Palembang dengan nangka muda, masakan tradisional bergizi.', '4-6 tahun', 4, ['Ikan Patin' => 80, 'Nangka Muda' => 40, 'Beras Putih' => 120, 'Tomat' => 20], "1. Bersihkan ikan patin, potong per porsi\n2. Kupas nangka muda, potong dadu, rendam air garam\n3. Rebus nangka muda 15 menit hingga setengah empuk\n4. Tambahkan ikan patin dan irisan tomat\n5. Bumbui dengan garam, asam jawa, dan cabai utuh\n6. Masak dengan api kecil 15 menit\n7. Sajikan pindang hangat dengan nasi putih", 3],
            ['Nasi Kuning Ayam Suwir Urap', 'nasi-kuning-ayam-suwir-urap', 'Nasi kuning harum kunyit dengan ayam suwir dan urap sayur, menu nusantara lengkap.', '4-6 tahun', 4, ['Beras Putih' => 120, 'Daging Ayam' => 60, 'Kangkung' => 20, 'Kelapa Parut' => 20, 'Kacang Panjang' => 20], "1. Masak nasi kuning: beras + santan + kunyit + daun salam\n2. Rebus ayam hingga empuk, suwir-suwir\n3. Tumis ayam suwir dengan sedikit kecap\n4. Rebus kangkung dan kacang panjang, tiriskan\n5. Sangrai kelapa parut, campurkan dengan sayuran rebus\n6. Tata nasi kuning di piring berbentuk tumpeng kecil\n7. Sajikan dengan ayam suwir dan urap sayur", 3],
            ['Sop Ikan Tongkol Sayuran', 'sop-ikan-tongkol-sayuran', 'Sop ikan tongkol segar dengan aneka sayuran, kuah bening hangat berprotein.', '4-6 tahun', 4, ['Ikan Tongkol' => 70, 'Kentang' => 40, 'Wortel' => 25, 'Bayam' => 20, 'Beras Putih' => 120], "1. Potong ikan tongkol per porsi\n2. Kupas kentang dan wortel, potong dadu\n3. Didihkan air, masukkan kentang dan wortel\n4. Setelah 10 menit, masukkan ikan tongkol\n5. Masak 10 menit hingga ikan matang\n6. Tambahkan bayam terakhir, masak 2 menit\n7. Beri garam dan merica\n8. Sajikan sop hangat dengan nasi", 3],
            ['Bebek Goreng Lalapan Sambal', 'bebek-goreng-lalapan-sambal', 'Bebek goreng empuk khas Madura dengan lalapan segar dan sambal.', '4-6 tahun', 4, ['Daging Bebek' => 80, 'Kangkung' => 25, 'Tomat' => 20, 'Beras Putih' => 120], "1. Bersihkan bebek, potong sesuai porsi\n2. Ungkep bebek dengan bumbu rempah hingga empuk\n3. Goreng bebek hingga garing kulit kecokelatan\n4. Rebus kangkung sebentar untuk lalapan\n5. Iris tomat segar\n6. Masak nasi putih\n7. Tata nasi, bebek goreng, dan lalapan\n8. Sajikan dengan sambal ringan", 3],
            ['Pepes Ikan Kembung Kemangi', 'pepes-ikan-kembung-kemangi', 'Pepes ikan kembung harum kemangi dibungkus daun pisang, kaya omega-3.', '4-6 tahun', 4, ['Ikan Kembung' => 80, 'Tomat' => 20, 'Beras Putih' => 120], "1. Bersihkan ikan kembung, buang sisik dan isi perut\n2. Lumuri ikan dengan bumbu kuning dan garam\n3. Iris tomat tipis, siapkan daun kemangi\n4. Layukan daun pisang di atas api\n5. Bungkus ikan dengan tomat dan kemangi dalam daun pisang\n6. Kukus 25 menit hingga matang dan harum\n7. Sajikan pepes dengan nasi putih hangat", 3],
            ['Rendang Daging Sapi Kentang', 'rendang-daging-sapi-kentang', 'Rendang daging sapi khas Minang dengan kentang, protein tinggi dan lezat.', '4-6 tahun', 4, ['Daging Sapi' => 60, 'Kentang' => 50, 'Santan' => 50, 'Beras Putih' => 120], "1. Potong daging sapi dadu besar\n2. Kupas kentang, potong dadu agak besar\n3. Tumis bumbu rendang hingga harum\n4. Masukkan daging, aduk hingga berubah warna\n5. Tuang santan, masak api kecil 1 jam\n6. Setelah daging empuk, masukkan kentang\n7. Masak hingga kuah mengering dan berminyak\n8. Sajikan rendang dengan nasi putih", 3],
            ['Sayur Lodeh Terong Tempe', 'sayur-lodeh-terong-tempe', 'Sayur lodeh terong dan tempe santan, lauk nabati khas Jawa bergizi.', '4-6 tahun', 4, ['Terong' => 40, 'Tempe' => 40, 'Santan' => 40, 'Kacang Panjang' => 25, 'Beras Putih' => 120], "1. Potong terong memanjang, rendam air garam\n2. Potong tempe dadu, goreng sebentar\n3. Potong kacang panjang 3 cm\n4. Didihkan santan encer dengan bumbu lodeh\n5. Masukkan terong dan kacang panjang\n6. Masak 10 menit, tambahkan tempe goreng\n7. Masak 5 menit lagi, koreksi rasa\n8. Sajikan lodeh hangat dengan nasi", 3],
            ['Cah Kangkung Udang Bawang', 'cah-kangkung-udang-bawang', 'Cah kangkung tumis udang ala masakan rumahan, cepat saji dan bergizi.', '4-6 tahun', 4, ['Kangkung' => 50, 'Udang' => 40, 'Beras Putih' => 120], "1. Petik kangkung, potong batang dan daunnya\n2. Kupas udang, buang kepala dan kulit\n3. Iris bawang putih tipis\n4. Panaskan minyak, tumis bawang putih hingga harum\n5. Masukkan udang, tumis hingga berubah warna\n6. Tambahkan kangkung, aduk cepat dengan api besar\n7. Beri sedikit garam dan kecap, masak 3 menit\n8. Sajikan dengan nasi putih", 3],
            ['Soto Betawi Daging Kentang', 'soto-betawi-daging-kentang', 'Soto Betawi dengan daging sapi dan kentang dalam kuah santan gurih.', '4-6 tahun', 4, ['Daging Sapi' => 50, 'Kentang' => 40, 'Santan' => 40, 'Tomat' => 15, 'Beras Putih' => 120], "1. Rebus daging sapi hingga empuk, potong dadu\n2. Kupas kentang, potong dadu, goreng setengah matang\n3. Tumis bumbu soto hingga harum\n4. Masukkan kaldu daging dan santan\n5. Tambahkan kentang goreng dan irisan tomat\n6. Masak hingga mendidih dan kentang empuk\n7. Sajikan soto dengan nasi putih dan pelengkap", 3],
            ['Ikan Bakar Bumbu Rujak Lalapan', 'ikan-bakar-bumbu-rujak-lalapan', 'Ikan bakar bumbu rujak pedas manis dengan lalapan sayur segar.', '4-6 tahun', 4, ['Ikan Nila' => 80, 'Tomat' => 20, 'Kangkung' => 25, 'Beras Putih' => 120], "1. Bersihkan ikan nila, kerat badannya\n2. Haluskan bumbu rujak: cabai, tomat, gula, garam\n3. Lumuri ikan dengan bumbu rujak, marinasi 15 menit\n4. Panggang ikan di atas bara atau teflon\n5. Bolak-balik hingga matang dan bumbu mengering\n6. Siapkan lalapan kangkung rebus\n7. Sajikan dengan nasi putih dan lalapan", 3],
            ['Tumis Cumi Kacang Panjang', 'tumis-cumi-kacang-panjang', 'Tumis cumi-cumi segar dengan kacang panjang kecap, lauk cepat saji.', '4-6 tahun', 4, ['Cumi-Cumi' => 60, 'Kacang Panjang' => 30, 'Beras Putih' => 120], "1. Bersihkan cumi, buang tinta dan tulang rawan\n2. Potong cumi berbentuk cincin\n3. Potong kacang panjang 3 cm\n4. Tumis bawang merah dan bawang putih hingga harum\n5. Masukkan cumi, tumis cepat 2 menit\n6. Tambahkan kacang panjang dan kecap manis\n7. Aduk rata, masak 3 menit api besar\n8. Sajikan dengan nasi putih", 3],
            ['Sayur Kelor Jagung Tahu', 'sayur-kelor-jagung-tahu', 'Sayur bening daun kelor dengan jagung dan tahu, superfood lokal bergizi tinggi.', '4-6 tahun', 4, ['Daun Kelor' => 25, 'Jagung Manis' => 30, 'Tahu' => 30, 'Beras Putih' => 120], "1. Petik daun kelor dari tangkainya\n2. Pipil jagung manis dari tongkol\n3. Potong tahu dadu kecil\n4. Didihkan air, masukkan jagung terlebih dahulu\n5. Setelah 10 menit, masukkan tahu\n6. Tambahkan daun kelor, masak 3 menit saja\n7. Beri garam secukupnya\n8. Sajikan sayur bening hangat dengan nasi", 3],
            ['Semur Daging Telur Kentang', 'semur-daging-telur-kentang', 'Semur daging sapi dengan telur rebus dan kentang, masakan rumahan klasik.', '4-6 tahun', 4, ['Daging Sapi' => 50, 'Telur Ayam' => 50, 'Kentang' => 50, 'Beras Putih' => 120], "1. Potong daging sapi dadu, rebus hingga empuk\n2. Rebus telur, kupas kulitnya\n3. Kupas kentang, potong dadu, goreng sebentar\n4. Tumis bawang merah dan bawang putih\n5. Masukkan daging, tambahkan kecap manis dan air\n6. Masak 15 menit, masukkan telur dan kentang\n7. Masak hingga kuah mengental dan bumbu meresap\n8. Sajikan semur hangat dengan nasi", 3],
            ['Nasi Bakar Isi Ikan Teri Sambal', 'nasi-bakar-isi-ikan-teri-sambal', 'Nasi bakar dalam daun pisang berisi ikan teri sambal, menu praktis dan lezat.', '4-6 tahun', 4, ['Beras Putih' => 120, 'Ikan Teri' => 30, 'Tempe' => 30, 'Tomat' => 15], "1. Masak nasi putih\n2. Goreng ikan teri hingga garing\n3. Cincang tempe, goreng hingga keemasan\n4. Ulek cabai, tomat, garam jadi sambal\n5. Campurkan nasi, ikan teri, tempe, dan sedikit sambal\n6. Bungkus dengan daun pisang, semat lidi\n7. Panggang nasi bakar di atas bara atau teflon\n8. Sajikan hangat", 3],
            ['Sup Kerang Tahu Sayuran', 'sup-kerang-tahu-sayuran', 'Sup kerang segar dengan tahu lembut dan sayuran, kaya mineral dan protein.', '4-6 tahun', 4, ['Kerang' => 50, 'Tahu' => 30, 'Wortel' => 20, 'Bayam' => 15, 'Beras Putih' => 120], "1. Cuci kerang bersih, rendam air garam 30 menit\n2. Potong tahu dadu kecil\n3. Kupas wortel, potong tipis\n4. Didihkan air, masukkan kerang hingga cangkang terbuka\n5. Tambahkan wortel dan tahu, masak 5 menit\n6. Petik bayam, masukkan terakhir\n7. Beri garam dan merica secukupnya\n8. Sajikan sup hangat dengan nasi", 3],
        ];

        foreach ($anak as $r) { $makeRecipe($r); }

        // ═══════════════════════════════════════════════════════════════════
        // CAMILAN SEHAT — Resep Lokal
        // ═══════════════════════════════════════════════════════════════════

        $camilan = [
            ['Bubur Kacang Hijau Santan', 'bubur-kacang-hijau-santan', 'Bubur kacang hijau khas pasar tradisional dengan santan, kaya protein nabati dan zat besi.', '1-3 tahun', 5, ['Kacang Hijau' => 40, 'Santan' => 30], "1. Rendam kacang hijau 2 jam, cuci bersih\n2. Rebus kacang hijau dengan air hingga lunak (30 menit)\n3. Tambahkan santan encer, aduk perlahan\n4. Beri sedikit gula aren dan garam\n5. Masak hingga kacang mekar dan kuah mengental\n6. Sajikan hangat dalam mangkuk", 3],
            ['Nagasari Pisang Daun Pisang', 'nagasari-pisang-daun-pisang', 'Kue nagasari tradisional dari tepung beras dengan pisang, dibungkus daun pisang.', '1-3 tahun', 5, ['Pisang' => 60, 'Beras Putih' => 30, 'Santan' => 30], "1. Campurkan tepung beras dengan santan, aduk rata\n2. Masak adonan di atas api kecil sambil diaduk hingga kental\n3. Kupas pisang, potong-potong memanjang\n4. Siapkan daun pisang, layukan sebentar\n5. Ambil satu sendok adonan, letakkan di daun pisang\n6. Taruh potongan pisang di tengah, tutup adonan\n7. Bungkus rapi, kukus 20 menit\n8. Sajikan setelah agak dingin", 3],
            ['Getuk Ubi Jalar Kelapa', 'getuk-ubi-jalar-kelapa', 'Getuk ubi jalar tradisional dengan taburan kelapa parut, manis alami dan berenergi.', '1-3 tahun', 5, ['Ubi Jalar' => 80, 'Kelapa Parut' => 20], "1. Kupas ubi jalar, potong-potong, cuci\n2. Kukus ubi hingga empuk sekitar 20 menit\n3. Angkat, tumbuk ubi selagi panas\n4. Tambahkan sedikit gula, aduk rata\n5. Bentuk adonan sesuai selera (bulat, lonjong)\n6. Gulingkan di atas kelapa parut segar\n7. Tata di piring, sajikan", 3],
            ['Wedang Jahe Pisang Rebus', 'wedang-jahe-pisang-rebus', 'Pisang rebus hangat dengan kuah gula aren, camilan kampung yang mengenyangkan.', '4-6 tahun', 5, ['Pisang' => 100], "1. Pilih pisang kepok atau raja yang matang\n2. Cuci pisang, rebus dengan kulitnya dalam air mendidih\n3. Masak 15-20 menit hingga kulit berubah gelap\n4. Angkat, kupas kulitnya\n5. Iris gula aren, rebus dengan air dan jahe geprek\n6. Sajikan pisang rebus hangat dengan kuah gula aren", 3],
            ['Kue Lumpur Labu Kuning', 'kue-lumpur-labu-kuning', 'Kue lumpur dari labu kuning lokal, lembut manis dan kaya vitamin A.', '4-6 tahun', 5, ['Labu Kuning' => 60, 'Telur Ayam' => 30, 'Santan' => 20], "1. Kukus labu kuning hingga empuk, haluskan\n2. Kocok telur dengan gula hingga mengembang\n3. Campurkan labu halus, santan, dan tepung terigu\n4. Aduk rata hingga adonan lembut\n5. Panaskan cetakan kue lumpur, olesi minyak\n6. Tuang adonan, masak api kecil hingga matang\n7. Angkat, sajikan setelah dingin", 3],
            ['Dadar Gulung Kelapa', 'dadar-gulung-kelapa', 'Dadar gulung isi kelapa parut dan gula aren, jajanan pasar bergizi.', '4-6 tahun', 5, ['Telur Ayam' => 30, 'Kelapa Parut' => 40], "1. Masak kelapa parut dengan gula aren dan sedikit air\n2. Aduk hingga gula meresap dan air mengering, sisihkan\n3. Kocok telur, campurkan dengan tepung dan air\n4. Tambahkan pewarna hijau pandan, aduk rata\n5. Buat dadar tipis di wajan datar\n6. Isi dadar dengan kelapa parut bergula\n7. Gulung rapi, sajikan", 3],
            ['Onde-Onde Kacang Hijau', 'onde-onde-kacang-hijau', 'Onde-onde isi kacang hijau dengan wijen, camilan tradisional kaya protein.', '4-6 tahun', 5, ['Kacang Hijau' => 30, 'Ubi Jalar' => 40], "1. Rendam kacang hijau, rebus hingga empuk, haluskan\n2. Masak kacang hijau halus dengan gula, buat isian\n3. Kukus ubi jalar, haluskan sebagai bahan kulit\n4. Campurkan ubi halus dengan tepung ketan, uleni\n5. Ambil satu sendok adonan, isi dengan kacang hijau\n6. Bulatkan, gulingkan di atas wijen\n7. Goreng dengan api kecil hingga mengembang keemasan", 3],
            ['Bubur Sumsum Santan', 'bubur-sumsum-santan', 'Bubur sumsum lembut dari tepung beras dengan kuah santan gula aren.', '1-3 tahun', 5, ['Beras Putih' => 30, 'Santan' => 40], "1. Larutkan tepung beras dengan air, saring\n2. Masak larutan dengan api kecil sambil terus diaduk\n3. Tambahkan sedikit garam dan daun pandan\n4. Aduk hingga mengental dan matang\n5. Untuk kuah: rebus santan dengan gula aren\n6. Tuang bubur sumsum ke mangkuk\n7. Siram dengan kuah santan gula aren\n8. Sajikan hangat", 3],
            ['Es Pisang Ijo', 'es-pisang-ijo', 'Es pisang ijo khas Makassar, pisang dibungkus adonan hijau dan kuah santan.', '4-6 tahun', 5, ['Pisang' => 80, 'Santan' => 40], "1. Campurkan tepung beras, tepung kanji, air, dan pewarna hijau\n2. Masak adonan sambil diaduk hingga kental\n3. Kupas pisang raja, balut dengan adonan hijau\n4. Kukus pisang berbalut adonan 15 menit\n5. Dinginkan, potong-potong\n6. Buat kuah: rebus santan dengan gula dan garam\n7. Tata pisang ijo di mangkuk, siram kuah\n8. Tambahkan es batu, sajikan", 3],
            ['Kue Cucur Gula Aren', 'kue-cucur-gula-aren', 'Kue cucur tradisional dari tepung beras dan gula aren, renyah pinggirnya.', '4-6 tahun', 5, ['Beras Putih' => 40, 'Kelapa Parut' => 15], "1. Larutkan gula aren dengan air hangat\n2. Campurkan tepung beras dengan larutan gula aren\n3. Aduk rata, diamkan 30 menit agar mengembang\n4. Panaskan minyak dalam wajan cekung\n5. Tuang satu sendok adonan ke tengah wajan\n6. Goreng api kecil hingga pinggir renyah, tengah empuk\n7. Angkat, tiriskan\n8. Sajikan dengan taburan kelapa parut", 3],
            ['Jus Pepaya Susu', 'jus-pepaya-susu', 'Jus pepaya segar dengan susu, kaya vitamin C, enzim papain, dan kalsium.', '1-3 tahun', 5, ['Pepaya' => 80, 'Susu UHT' => 100], "1. Kupas pepaya matang, buang biji, potong dadu\n2. Masukkan pepaya ke dalam blender\n3. Tambahkan susu UHT dingin\n4. Blender hingga halus dan tercampur rata\n5. Tuang ke gelas, sajikan segera\n6. Bisa ditambahkan es batu jika suka", 3],
            ['Pisang Goreng Tepung Beras', 'pisang-goreng-tepung-beras', 'Pisang goreng krispi tepung beras, camilan rakyat energi tinggi.', '4-6 tahun', 5, ['Pisang' => 80, 'Beras Putih' => 20], "1. Kupas pisang kepok matang, belah dua memanjang\n2. Campurkan tepung beras dengan sedikit air dan garam\n3. Aduk hingga adonan tidak terlalu kental\n4. Celupkan pisang ke dalam adonan tepung\n5. Panaskan minyak goreng secukupnya\n6. Goreng pisang hingga keemasan dan garing\n7. Angkat, tiriskan, sajikan hangat", 3],
            ['Kolak Singkong Kelapa Muda', 'kolak-singkong-kelapa-muda', 'Kolak singkong dengan santan dan gula aren, hangat manis tradisional.', '1-3 tahun', 5, ['Singkong' => 60, 'Santan' => 40], "1. Kupas singkong, potong dadu, cuci bersih\n2. Rebus singkong dalam air hingga setengah empuk\n3. Iris gula aren, tambahkan ke rebusan\n4. Tuang santan, aduk perlahan\n5. Tambahkan daun pandan untuk aroma\n6. Masak api kecil hingga singkong empuk dan kuah mengental\n7. Sajikan hangat dalam mangkuk", 3],
            ['Labu Kuning Kukus Kelapa', 'labu-kuning-kukus-kelapa', 'Labu kuning kukus taburan kelapa parut segar, manis alami dan kaya beta-karoten.', '1-3 tahun', 5, ['Labu Kuning' => 60, 'Kelapa Parut' => 15], "1. Kupas labu kuning, buang biji, potong dadu besar\n2. Tata potongan labu di atas kukusan\n3. Kukus 15-20 menit hingga empuk\n4. Angkat, tata di piring\n5. Taburi kelapa parut segar di atasnya\n6. Bisa ditambahkan sedikit gula jika suka\n7. Sajikan hangat atau suhu ruang", 3],
            ['Smoothie Mangga Pisang', 'smoothie-mangga-pisang-lokal', 'Smoothie segar mangga lokal dan pisang, kaya vitamin C dan kalium alami.', '1-3 tahun', 5, ['Mangga' => 60, 'Pisang' => 50, 'Susu UHT' => 80], "1. Kupas mangga matang, potong dadu\n2. Kupas pisang, potong-potong\n3. Masukkan mangga dan pisang ke blender\n4. Tambahkan susu UHT\n5. Blender hingga halus dan creamy\n6. Tuang ke gelas, sajikan segera\n7. Bisa ditambahkan es batu jika suka", 3],
        ];

        foreach ($camilan as $r) { $makeRecipe($r); }
    }
}
